[build]
  command = "./build.sh"
  functions = "functions"
  publish = "dist"

[build.environment]
  GO_IMPORT_PATH = "github.com/spotlightpa/almanack"
  GO111MODULE = "on"
  NODE_VERSION = "12"
  GIMME_GO_VERSION = "1.13.4"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/almanack-api/:splat"
  force = true
  status = 200

[[redirects]]
  from = "/login"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/articles/*"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404
  force = false
