[build]
  command = "./build.sh"
  functions = "functions"
  publish = "dist"

[build.environment]
  GO_IMPORT_PATH = "github.com/spotlightpa/almanack"
  GO111MODULE = "on"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/almanack-api/:splat"
  status = 200
